/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#95d4b3",
        "surface-bright": "#f8f9fa",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdbcf",
        "outline-variant": "#c1c8c2",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#cd9d6d",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "tertiary-container": "#56340e",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed-dim": "#ebbcac",
        "on-secondary-fixed-variant": "#603f33",
        "on-surface-variant": "#414844",
        primary: "#002d1c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002114",
        background: "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#623f18",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "secondary-container": "#fdcdbc",
        "surface-container": "#edeeef",
        "on-background": "#191c1d",
        "surface-tint": "#2c694e",
        "tertiary-fixed-dim": "#f0bd8b",
        "tertiary-fixed": "#ffdcbd",
        outline: "#717973",
        "surface-container-low": "#f3f4f5",
        error: "#ba1a1a",
        "on-secondary-fixed": "#2e150b",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#76b394",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#95d4b3",
        tertiary: "#3b1f00",
        surface: "#f8f9fa",
        "on-secondary-container": "#795548",
        "primary-container": "#00452e",
        secondary: "#7a5649",
        "primary-fixed": "#b1f0ce",
        "on-primary-fixed-variant": "#0e5138",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed": "#2c1600",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
